name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      
      - name: Autofix
        run: |
          npx prettier -w **.md
          gofmt -w $(find . -name '*.go')

      - uses: autofix-ci/action@v1
        with:
          fail-fast: false
